### PR TITLE
Commerce 6609 brians naming changes

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
Brian's requested changes https://github.com/brianchandotcom/liferay-portal/pull/113585#issuecomment-1046961002

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:test:stable

**Pull request closed without merging**
