### PR TITLE
COMMERCE-5475 Dispatch Talend task fails but Dispatch Log shows SUCCESSFUL state

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/shuyangzhou/liferay-portal/pull/9748. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/9ade3498aa4d~3...9ade3498aa4d)

**Pull request closed without merging**
