### PR TITLE
COMMERCE-4969 Integration tests for Dispatch task execution overlap feature

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/338. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/a9ce669910a2~3...a9ce669910a2)

**Pull request closed without merging**
