### PR TITLE
Commerce 7988

### PR DESCRIPTION
**Pull request by joemduffy**
Just to show Igor code...

### CODE REVIEW

**Comment by joemduffy** [comment]
ci:test:sf

**Comment by joemduffy** [comment]
ci:test:sf

**Comment by joemduffy** [comment]
ci:test:sf

**Comment by joemduffy** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
- Move `com.liferay.portal.kernel.exception.InvalidDelimiterException` to batch-engine-api. Introduce service.xml exception `BatchEngineImportTaskPropertyException`
- in `com.liferay.batch.engine.internal.reader.BatchEngineImportTaskItemReaderFactory#create` replace `BatchEngineImportTask batchEngineImportTask` parameter with `Map<String, Serializable> parameters` and also update constructor `com.liferay.batch.engine.internal.reader.CSVBatchEngineImportTaskItemReaderImpl#CSVBatchEngineImportTaskItemReaderImpl` to accept Map properties and extract delimiter in CSV CSVBatchEngineImportTaskItemReaderImpl...
- remember case statement and idea with:
`private static String[] _escapedDelimiters = {
		StringPool.OPEN_BRACKET,
		StringPool.CLOSE_BRACKET, StringPool.OPEN_PARENTHESIS, 
		StringPool.CLOSE_PARENTHESIS, StringPool.OPEN_CURLY_BRACE, 
		StringPool.CLOSE_CURLY_BRACE, StringPool.QUESTION, StringPool.PERIOD, StringPool.STAR, 
		StringPool.CARET, StringPool.DOLLAR, StringPool.PLUS, StringPool.EXCLAMATION, StringPool.PIPE
	};
`

**Pull request closed without merging**
