### PR TITLE
Commerce-5141 Update schedule/unschedule procedures for memory scheduler jobs

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/384. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/2721792ad624~5...2721792ad624)

**Pull request closed without merging**
