### PR TITLE
COMMERCE-4934

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@igorbeslic see my comments in https://github.com/brianchandotcom/liferay-portal/pull/94930

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/matijapetanjek/liferay-portal/pull/19. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/8cd4b806dc05~9...8cd4b806dc05)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/94980. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/9713dd381f13~10...9713dd381f13)

**Pull request closed without merging**
