### PR TITLE
Commerce-6529 Implement dispatch-batch-web module

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/1310. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/3185f0e20c89~7...3185f0e20c89)

**Pull request closed without merging**
