### PR TITLE
Commerce 5334 - Dispatch task executor name is not used

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/454. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/4331c408f5a7~2...4331c408f5a7)

**Pull request closed without merging**
