### PR TITLE
Commerce-5588 Change column type

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/591. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/3407ffa831fb~2...3407ffa831fb)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/593. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/d6b1c5e63205~1...d6b1c5e63205)

**Pull request closed without merging**
