### PR TITLE
COMMERCE-5452 Remove duplicated language keys

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/569. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/884234c3d824~5...884234c3d824)

**Pull request closed without merging**
