### PR TITLE
COMMERCE-4880

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@igorbeslic see my comments in https://github.com/brianchandotcom/liferay-portal/pull/96737

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/432. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/887b4702375f~2...887b4702375f)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/96820. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/b2f067ef8dbc~3...b2f067ef8dbc)

**Pull request closed without merging**
