### PR TITLE
COMMERCE-9001 - headless-batch-engine-impl - allow downloading origin…

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
…al file for failed imports

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
great!! Thank you Mahmoud.

**Pull request closed without merging**
