### PR TITLE
Commerce-5391  rename attributes - upgrade process + deprecate methods

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/475.

**Pull request closed without merging**
