### PR TITLE
Commerce-5657 Implement basic scheduled task resolver

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/638. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/45cb2c26c7c2~12...45cb2c26c7c2)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/660. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/20e2d67bf353~29...20e2d67bf353)

**Pull request closed without merging**
