### PR TITLE
COMMERCE-8104 (backend part) Clicking on template should open it for edit instead of starting a new export/import flow

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:stop

**Pull request closed without merging**
