### PR TITLE
COMMERCE-4882 Dispatch Executor Must Limit Concurrent Execution of Particular Trigger in Cluster Environment

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/matijapetanjek/liferay-portal/pull/20. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/0f1a0aca8dcf~12...0f1a0aca8dcf)

**Pull request closed without merging**
