### PR TITLE
LPS-127481 Do not run the job until all repositories are ready

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/604. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/f103a2659e5a~2...f103a2659e5a)

**Pull request closed without merging**
