### PR TITLE
matija LPS 174373 batch deploy on startup

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-174373 add exported interface to the batch engine API
- LPS-174373 use the interface in the current implementations
- LPS-174373 implement a processor interface for a batch engine processor service
- LPS-174373 make BatchEngineAutoDeployListener provide the service
- LPS-174373 implement batch engine processing from bundles
- LPS-174373 tests
- LPS-174373 rename
- LPS-174373 no reason to have public -> private -> public method calls
- LPS-174373 update test data
- LPS-174373 extract code from AutoDeployListener to a more appropriate classes
- LPS-174373 batch-engine-api - .bnd
- LPS-174373 batch-engine-service - update tests
- LPS-174373 batch-engine - move to util to reuse it in other classes
- LPS-174373 batch-engine - gradle - add dependency
- LPS-174373 batch-engine - bnd
- LPS-174373 batch-engine - TEST - use Util
- LPS-174373 batch-engine - INTEGRATION TEST - explode jars to easier track content in Git
- LPS-174373 batch-engine - INTEGRATION TEST - use Util to compress
- LPS-174373 batch-engine - INTEGRATION TEST - runs in OSGi so use bundle API to build zip

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test

**Comment by rotty3000** [comment]
@igorbeslic when you finally send this ahead to bchan please also let @tinatian and @yuhai know, thanks a lot.

**Comment by igorbeslic** [comment]
test pass

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
cc  @tinatian  @yuhai

**Comment by rotty3000** [comment]
@igorbeslic as asked by  @tinatian I need to push another commit to delete the auto deployer. Sorry :(

**Comment by igorbeslic** [comment]
@rotty3000 OK - I'll close this PR and wait for your new update

**Pull request closed without merging**
