### PR TITLE
Simple request to Asah Backend using Petra JSON WS Client

### PR DESCRIPTION
**Pull request by darquesdev**

### CODE REVIEW

**Comment by darquesdev** [comment]
Hi @igorbeslic ,

As we have already spoken by email, I send you a PR that reproduces the error in a prod-environment.
To reproduce it you only have to deploy the module 'segments-service'.
Path: liferay-portal/modules/apps/segments/segments-service

The known error will be shown in console.

@epgarcia

**Comment by igorbeslic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by igorbeslic** [comment]
@darquesdev I think you miss keystore settings with trusted certificates. In LCS we have keystore with loaded liferay public key in certificate.
I could probably update README... let me test more (I still have to add multiple parameters)

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Not sure if that's the problem. Here:
https://github.com/igorbeslic/liferay-portal/pull/29
A simple request to ASAH with different clients: JAX-RS and directly using Apache HttpClient Both working as expected.
Anyway, share some info about configuring trusted certificates for the WS client and we'lll try it out.
Thanks!

**Pull request closed without merging**
