### PR TITLE
LPS-159040 DI - Job Scheduler - xss escaping

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/121457

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
