### PR TITLE
Commerce-2820-2 Fix SonarQube Blocking Critical and Major issues

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86182. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/55bde121f9b9~1...55bde121f9b9)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86183. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/be073717e8ed~1...be073717e8ed)

**Pull request closed without merging**
