### PR TITLE
COMMERCE-7562 - As a practitioner exporting a file, I want to know the status of the export

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
sent to https://github.com/liferay-commerce/liferay-portal/pull/1955

**Pull request closed without merging**
