### PR TITLE
COMMERCE-7554 - batch-planner-service - Java changes - Updating Batch…

### PR DESCRIPTION
**Pull request by MahmoudAzzam**
…PlannerPlan.active to false onAfterRemove

### CODE REVIEW

**Comment by MahmoudAzzam** [comment]
ci:test:sf

**Comment by MahmoudAzzam** [comment]
ci:test:relevant

**Comment by MahmoudAzzam** [comment]
@igorbeslic , I used onAfterRemove instead of onDelete, please let me know if it needs changing

**Comment by igorbeslic** [comment]
I updated code
https://github.com/liferay-commerce/liferay-portal/pull/2387

we can discuss change in Call

**Pull request closed without merging**
