### PR TITLE
Commerce-5731 NPE if TalendExecutor is not available

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/673. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/2ebd25758df4~2...2ebd25758df4)

**Pull request closed without merging**
