### PR TITLE
COMMERCE-5396 Test method passes but throws error in the log

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/477. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/ef6645ac3c73~2...ef6645ac3c73)

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/liferay-commerce/liferay-portal/pull/478. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/afa56ed12833~6...afa56ed12833)

**Pull request closed without merging**
