### PR TITLE
COMMERCE-2475 - Rename fields + minor fixes

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
Pull request submitted to https://github.com/matijapetanjek/liferay-portal/pull/9. [See changes here.](https://github.com/igorbeslic/liferay-portal/compare/9450677b91b2~6...9450677b91b2) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
