### PR TITLE
Commerce 4927 - Dispatch Integration Test Should test more than one company and sheduledJob state

### PR DESCRIPTION
**Pull request by matijapetanjek**
Current tests already create multiple companies and test multiple portal instance scenarios. I've just added taskClusterMode parameter to existing tests! Please review, thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
